package main

type AutoGenerated struct {
	Results []struct {
		AddressComponents []struct {
			LongName  string   `json:"long_name"`
			ShortName string   `json:"short_name"`
			Types     []string `json:"types"`
		} `json:"address_components"`
		FormattedAddress string `json:"formatted_address"`
		Geometry         struct {
			Bounds struct {
				Northeast struct {
					Lat float64 `json:"lat"`
					Lng float64 `json:"lng"`
				} `json:"northeast"`
				Southwest struct {
					Lat float64 `json:"lat"`
					Lng float64 `json:"lng"`
				} `json:"southwest"`
			} `json:"bounds"`
			Location struct {
				Lat float64 `json:"lat"`
				Lng float64 `json:"lng"`
			} `json:"location"`
			LocationType string `json:"location_type"`
			Viewport     struct {
				Northeast struct {
					Lat float64 `json:"lat"`
					Lng float64 `json:"lng"`
				} `json:"northeast"`
				Southwest struct {
					Lat float64 `json:"lat"`
					Lng float64 `json:"lng"`
				} `json:"southwest"`
			} `json:"viewport"`
		} `json:"geometry"`
		PlaceID string   `json:"place_id"`
		Types   []string `json:"types"`
	} `json:"results"`
	Status string `json:"status"`
}


type RetVal struct {
	Artists []Artist
	Option []string
	Locations []string
}

type City struct {
	Lat float64 `json:"lat"`
	Lng float64 `json:"lng"`
}



type Artist struct{
	ID int `json:"id"`
	Image string `json:"image"`
	Name string `json:"name"`
	Members []string `json:"members"`
	CreationDate int `json:"creationDate"`
	FirstAlbum string `json:"firstAlbum`
	Locs Locations
	ConDates ConcertDates
	Rels Relation
	Coords []City
}


type Index struct {
	Index []Locations `json:"index"`
}

type Locations struct {
	ID int `json:"id"`
	Locations  []string `json:"locations"`
	Dates ConcertDates
}

type DateIndex struct {
	Index []ConcertDates `json:"index"`
}

type ConcertDates struct {
	ID int `json:"id"`
	Dates []string `json:"dates"`
}


type RelationIndex struct {
	Index []Relation `json:"index"`
}

type Relation struct {
	ID int `json:"id"`
	DatesLocations map[string][]string `json:"datesLocations`
}

